# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Varun Barad - Curious Developer
email: barad.varun29@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My online home where I post about new things I learn or find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://varunbarad.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: varun_barad
github_username:  VarunBarad
excerpt_separator: "<!-- end excerpt -->"
author:
  name: Varun Barad
  twitter: https://twitter.com/varun_barad
  picture: /assests/images/profile.png

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

collections:
  category:
    output: true
    permalink: /:collection/:name
  technology:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: technology
    values:
      layout: "technology"

# Kramdown settings
kramdown:
  auto_ids: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
