#!/usr/bin/env zsh

mkdir -p _eleventy/_includes
cp _includes/footer.html _eleventy/_includes/_footer.html
cp _includes/header.html _eleventy/_includes/_header.html
cp _includes/new_styles.html _eleventy/_includes/_new_styles.html
