#!/usr/bin/env zsh

cp favicon.png _eleventy/favicon.png

mkdir -p _eleventy/_includes
cp _includes/footer.html _eleventy/_includes/_footer.html
cp _includes/header.html _eleventy/_includes/_header.html
cp _includes/new_styles.html _eleventy/_includes/_new_styles.html

mkdir -p _eleventy/podcasts
cp podcasts/hpmor.xml _eleventy/podcasts/hpmor.xml
